# This workflow will install Python dependencies, run full checks defined in `.pre-commit-config.yaml` with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Jupyter Notebooks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  jupyter-notebooks:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install packages
      run: pip install .[develop]
    - name: Run Jupyter notebooks
      run: for note in `ls notebooks/*.ipynb`; do jupyter nbconvert --to html --execute $note; if [ $? != 0 ]; then echo $note; exit 1; fi; done
